spring.application.name=workshopmongo
spring.data.mongodb.uri=mongodb+srv://Cluster70986:anp9X1J2RXZP@cluster70986.y0ppfsy.mongodb.net/workshop_mongo?appName=Cluster70986
spring.data.mongodb.database=workshop_mongo