spring.application.name=workshopmongo
spring.profiles.active=local
spring.data.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster70986.y0ppfsy.mongodb.net/?appName=Cluster70986
spring.data.mongodb.database=workshop_mongo